DELETE http://localhost:8080/events/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MTQ4MjYzNjUsInVzZXJJZCI6MX0.HzSOIW8qX_hwy00zaB8UrYSdQjVRvw-URCWvOSB2EUI